name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Build Docker image inside GitHub Actions runner
      - name: Build Docker image
        run: |
          docker build -t my-html-app:latest .
          docker save my-html-app:latest > my-html-app.tar
          chmod 664 my-html-app.tar

      # 3. Copy image tarball to VPS
      - name: Transfer Docker image to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "my-html-app.tar,docker-compose.yml"
          target: "/root/app_t"

      # 4. Load & run container on VPS
      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/app_t
            docker load < /root/app_t/my-html-app.tar
            docker-compose up -d
